project:
  type: website
  output-dir: docs

website:
  title: "GG"
  favicon: GG-hex-tiny.png
  navbar:
    logo: |
      ![](GG-hex-small.png)
    pinned: true
    left: 
      - about.qmd
    right:
      - icon: github
        href: https://github.com/isu-graphicsgroup
      
format:
  html:
    theme: spacelab
    css: styles.css



